### ISSUE TITLE
histogram chart for job breakdowns and file breakdown

### ISSUE THREAD

**Issue by vahi** [pegasus-isi/pegasus-metrics#22]
we want a page that will allow us to display the number of workflows in various ranges. on top of page we should have 
from date, to date, dropdown to select files or jobs, range for files /jobs, dropdown to select what type of files/jobs for which we want a histogram 

the histogram x axis is number of files/ jobs ( dependent on what was selected)
y axis is the count of workflows

**Comment by juve** [comment]
Looks good to me
