### ISSUE TITLE
Map options are unclear

### ISSUE THREAD

**Issue by juve** [pegasus-isi/pegasus-metrics#4]
Right now we have these options for maps:

Top Hosts
Top Domains
Recent Runs
Recent Downloads
Top Downloads

Top X hosts for the last N months makes sense. It would be nice if we knew what X was though.

Top X domains for the last N months does not make sense. Domains have no location. We locate based on IP address. What is the location of the nasa.gov domain, for example?

Recent runs makes sense, but how is the result limited? Clearly we can't show a pin for all runs done in the last 12 months. There is no indication that the data is being limited.

Recent downloads makes sense. Again, we can't show all downloads, so what is the limit?

Top downloads also is confusing. Top downloads is determined by package (e.g. the CentOS 7 x86_64 RPM), but what is the location of a package?

**Comment by dcbriggs** [comment]
Top Domains and Top Downloads looks at the remote_addr field of the most recent entry in the database that has that domain.

I don't know how useful that makes Top Domains, but it definitely means that Top Downloads is not a useful metric to show.  I can remove that one from the list of options.

Recent runs and recent downloads currently have no limit (they did previously but we decided to remove that form from the metrics server).  We could try to do some form of pagination where users can look through X number of results at a time.

**Comment by juve** [comment]
Don't show more than 100 entries. Also, always print the number of markers being shown at the top, above the map.

For recent runs and recent downloads, just select distinct remote_addr in the time range limit 100.

Remove top downloads and top domains.

Rename top hosts to Top Planner Hosts. Rename Recent Runs to Recent Plans (assuming it came from planner_metrics and not dagman_metrics).
