### ISSUE TITLE
Add info windows to map markers

### ISSUE THREAD

**Issue by juve** [pegasus-isi/pegasus-metrics#5]
None of the markers on the maps have info windows. It would be nice to see, for example, when we have a recent download in, say, Sydney, what package was downloaded. Similarly, it would be nice, if we saw a recent planner run in New York, to have a link to the planner metrics page for that run.

**Comment by dcbriggs** [comment]
Right now the markers will just show the location associated with the marker.  Do we want to replace that with the package name/planner link, or include it as well?

**Comment by juve** [comment]
When we click on the marker, we want to be able to see information about what that marker represents. If it was a download, then we would like to see which package was downloaded. I'm talking about adding an Info Window.
![untitled](https://cloud.githubusercontent.com/assets/201949/6511991/92861af8-c325-11e4-8c1c-81ef5c750d55.png)
